task.class: Translation
task.params:
  src_data_pipeline.class: TEXTDataPipeline
  src_data_pipeline.params:
    subtokenizer: bpe
    subtokenizer_codes: /MSMT/en_zh/codes.bpe
    vocab_path: /MSMT/en_zh/vocab.en
  trg_data_pipeline.class: TextDataPipeline
  trg_data_pipeline.params:
    subtokenizer: bpe
    subtokenizer_codes: /MSMT/en_zh/codes.bpe
    vocab_path: /MSMT/en_zh/vocab.zh
  batch_size_per_gpu: 8196
  batch_by_tokens: true
  max_src_len: 256
  max_trg_len: 256
